### ISSUE TITLE
[Task]: Removing outdated distribution tags on packages

### ISSUE THREAD

**Issue by nstuyvesant** [carbon-design-system/carbon-charts#1597]
## Task

@theiliad - please run the following to remove the distribution tags on the previous versions now that 1.10.5 is the latest (except for angular).

```bash
# Cleanup core
npm dist-tag rm @carbon/charts@1.9.0-next.3 next
npm dist-tag rm @carbon/charts@1.9.0-rc.6 rc-1.9.0
npm dist-tag rm @carbon/charts@0.41.98-d3v5-latest-0.1 latest-dcv5

# Cleanup angular
npm dist-tag rm @carbon/charts-angular@1.9.0-rc.6 rc-1.9.0
npm dist-tag rm @carbon/charts-angular@0.41.98-d3v5-latest-0.1 latest-d3v5
# leave next tag on 1.10.5

# Cleanup react
npm dist-tag rm @carbon/charts-react@1.9.0-next.3 next
npm dist-tag rm @carbon/charts-react@1.9.0-rc.6 rc-1.9.0
npm dist-tag rm @carbon/charts-react@0.41.98-d3v5-latest-0.1 latest-d3v5

# Cleanup svelte
npm dist-tag rm @carbon/charts-svelte@1.9.0-next.3 next
npm dist-tag rm @carbon/charts-svelte@1.9.0-rc.6 rc-1.9.0
npm dist-tag rm @carbon/charts-svelte@0.41.98-d3v5-latest-0.1 latest-d3v5

# Cleanup vue
npm dist-tag rm @carbon/charts-vue@1.11.0 latest
npm dist-tag add @carbon/charts-vue@1.8.0 latest
npm dist-tag rm @carbon/charts-vue@1.9.0-rc.6 rc-1.9.0
npm dist-tag rm @carbon/charts-vue@0.41.98-d3v5-latest-0.1 latest-d3v5
```

### What priority level would this be in your opinion?

P0

**Comment by theiliad** [comment]
# Cleanup core

- [ ] npm dist-tag rm @carbon/charts@1.9.0-next.3 next
- [ ] npm dist-tag rm @carbon/charts@1.9.0-rc.6 rc-1.9.0
- [ ] npm dist-tag rm @carbon/charts@0.41.98-d3v5-latest-0.1 latest-d3v5

# Cleanup angular

- [ ] npm dist-tag rm @carbon/charts-angular@1.9.0-rc.6 rc-1.9.0
- [ ] npm dist-tag rm @carbon/charts-angular@0.41.98-d3v5-latest-0.1 latest-d3v5

# leave next tag on 1.10.5

# Cleanup react

- [ ] npm dist-tag rm @carbon/charts-react@1.9.0-next.3 next
- [ ] npm dist-tag rm @carbon/charts-react@1.9.0-rc.6 rc-1.9.0
- [ ] npm dist-tag rm @carbon/charts-react@0.41.98-d3v5-latest-0.1 latest-d3v5

# Cleanup svelte

- [ ] npm dist-tag rm @carbon/charts-svelte@1.9.0-next.3 next
- [ ] npm dist-tag rm @carbon/charts-svelte@1.9.0-rc.6 rc-1.9.0
- [ ] npm dist-tag rm @carbon/charts-svelte@0.41.98-d3v5-latest-0.1 latest-d3v5

# Cleanup vue

- [ ] npm dist-tag rm @carbon/charts-vue@1.11.0 latest
- [ ] npm dist-tag add @carbon/charts-vue@1.8.0 latest
- [ ] npm dist-tag rm @carbon/charts-vue@1.9.0-rc.6 rc-1.9.0
- [ ] npm dist-tag rm @carbon/charts-vue@0.41.98-d3v5-latest-0.1 latest-d3v5
