### ISSUE TITLE
Write a Medium announcement article for Figma Kit Alpha release

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-charts#1777]
```[tasklist]
### Tasks
- [x] Write draft
- [x] Submit draft to publication
- [x] Request imagery via [Thy's box note](https://ibm.ent.box.com/notes/1198232822537)
- [ ] Team review and edit draft
- [ ] Incorporate any changes, imagery
- [ ] Select a publish date
- [ ] Publish
```
