### ISSUE TITLE
[Restyle] Legends

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-charts#287]
Need to do a pass on restyling **legends** 

Enhancements needed for open issues:
- [ ] Legend position prop: https://github.com/carbon-design-system/carbon-charts/issues/279
- [ ] Legends covering chart https://github.com/carbon-design-system/carbon-charts/issues/191
- [ ] Legend with values https://github.com/carbon-design-system/carbon-charts/issues/145

**Comment by shixiedesign** [comment]
## [WIP] Design, guidance, and some spec for legends

### Visual styles

![(1) Legend styles](https://user-images.githubusercontent.com/15144993/62880649-80790380-bcf3-11e9-83fb-fc8dde2124b7.png)

### Interactions / behavior

![(2) Legend interactions](https://user-images.githubusercontent.com/15144993/62880650-80790380-bcf3-11e9-8f62-c272cf17e88f.png)

### Legend layout options

![(3) Position   layout](https://user-images.githubusercontent.com/15144993/62880651-81119a00-bcf3-11e9-8e56-9b23ffb24b98.png)

**Comment by theiliad** [comment]
#279

**Comment by shixiedesign** [comment]
### Overflow treatment design WIP

FYI @cameroncalder

![image](https://user-images.githubusercontent.com/15144993/63194044-9c064600-c034-11e9-989a-128f3aa2aa84.png)

**Comment by shixiedesign** [comment]
## Completed designs. Awaiting approval. 

### (1) Legend styles

![(1) Legend styles](https://user-images.githubusercontent.com/15144993/63200119-b137a080-c045-11e9-8d0e-5710e392773c.png)

### (2) Legend

![(2) Legend interactions](https://user-images.githubusercontent.com/15144993/63200120-b137a080-c045-11e9-8ce2-dff675f27d1a.png)

### (3) Position

![(3) Position](https://user-images.githubusercontent.com/15144993/63200121-b137a080-c045-11e9-964e-fe432f3aaf5c.png)

**Comment by theiliad** [comment]
**Remaining work:**

![image](https://user-images.githubusercontent.com/14989804/72081070-d87c5c00-32cb-11ea-8be4-82add81cf241.png)
![image](https://user-images.githubusercontent.com/14989804/72081093-e0d49700-32cb-11ea-8e79-610c0a299015.png)
![image](https://user-images.githubusercontent.com/14989804/72081134-f0ec7680-32cb-11ea-8c08-19aa7aafd03c.png)
![image](https://user-images.githubusercontent.com/14989804/72081146-f77aee00-32cb-11ea-92b2-7f348100e1e0.png)
![image](https://user-images.githubusercontent.com/14989804/72081158-fcd83880-32cb-11ea-8272-549573ea8561.png)
![image](https://user-images.githubusercontent.com/14989804/72081184-02ce1980-32cc-11ea-8c2b-f22fa4989d5a.png)

**Comment by tay1orjones** [comment]
Bumping this thread - the legends overflow is something we've gotten requests for, https://github.com/IBM/carbon-addons-iot-react/issues/1364

**Comment by theiliad** [comment]
> Bumping this thread - the legends overflow is something we've gotten requests for, [IBM/carbon-addons-iot-react#1364](https://github.com/IBM/carbon-addons-iot-react/issues/1364)

@tay1orjones truncations have already been implemented. This issue is still open only for other aspects of the legend specs

Here's a truncation demo https://carbon-design-system.github.io/carbon-charts/?path=/story/line--line-discrete-with-truncated-labels
